<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugSymbols>False</DebugSymbols>
    <DebugType>None</DebugType>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <PublishDir>./bin/K4-Zenith-Stats/</PublishDir>
  </PropertyGroup>
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="*">
      <PrivateAssets>none</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Dapper" Version="*" />
    <PackageReference Include="MySqlConnector" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ZenithAPI">
      <HintPath>$(ProjectDir)\..\..\src-api\bin\K4-ZenithAPI\K4-ZenithAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="KitsuneMenu">
      <HintPath>$(ProjectDir)/../../external-dlls/KitsuneMenu.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Update="$(ProjectDir)\lang\**\*.*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
