<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugSymbols>False</DebugSymbols>
    <DebugType>None</DebugType>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <PublishDir>./bin/K4-Zenith/plugins/K4-Zenith/</PublishDir>
  </PropertyGroup>
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="*">
      <PrivateAssets>none</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Dapper" Version="*" />
    <PackageReference Include="FluentMigrator" Version="*" />
    <PackageReference Include="FluentMigrator.Runner.MySql" Version="*" />
    <PackageReference Include="MaxMind.GeoIP2" Version="*" />
    <PackageReference Include="MySqlConnector" Version="*" />
    <PackageReference Include="Newtonsoft.Json" Version="*" />
    <PackageReference Include="YamlDotNet" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ZenithAPI">
      <HintPath>$(ProjectDir)\..\src-api\bin\K4-ZenithAPI\K4-ZenithAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="KitsuneMenu">
      <HintPath>$(ProjectDir)/../external-dlls/KitsuneMenu.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="K4ArenaSharedApi">
      <HintPath>$(ProjectDir)/../external-dlls/K4-ArenaSharedApi.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Update="$(ProjectDir)\lang\**\*.*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <Target Name="CopySharedApiToOutput" AfterTargets="Build">
    <Copy SourceFiles="$(ProjectDir)/../external-dlls/KitsuneMenu.dll" DestinationFolder="$(ProjectDir)/bin/K4-Zenith/shared/KitsuneMenu/" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
    <Copy SourceFiles="$(ProjectDir)\..\src-api\bin\K4-ZenithAPI\K4-ZenithAPI.dll" DestinationFolder="$(ProjectDir)/bin/K4-Zenith/shared/K4-ZenithAPI/" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
  </Target>
</Project>
